webtalk_init -webtalk_dir /mnt/hgfs/RISC-V/1_Cores/Verilog_BenchRV32I/vivado/BenchRV32.sim/sim_1/behav/xsim/xsim.dir/TOP_RV32_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 10 23:33:51 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7a2a3412-07f5-4816-ba35-e50a51b7cf63" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3bc1b56345364b0f80b20e59d8e0f703" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1895.999 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "131156_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2000111118 -regid "" -xml /mnt/hgfs/RISC-V/1_Cores/Verilog_BenchRV32I/vivado/BenchRV32.sim/sim_1/behav/xsim/xsim.dir/TOP_RV32_behav/webtalk/usage_statistics_ext_xsim.xml -html /mnt/hgfs/RISC-V/1_Cores/Verilog_BenchRV32I/vivado/BenchRV32.sim/sim_1/behav/xsim/xsim.dir/TOP_RV32_behav/webtalk/usage_statistics_ext_xsim.html -wdm /mnt/hgfs/RISC-V/1_Cores/Verilog_BenchRV32I/vivado/BenchRV32.sim/sim_1/behav/xsim/xsim.dir/TOP_RV32_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
